version: '3.8'

services:
  prometheus:
    image: docker.io/prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:Z
    networks:
      - internal
    ports:
      - "127.0.0.1:9090:9090"

  grafana:
    image: docker.io/grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - internal
    ports:
      - "127.0.0.1:3000:3000" 

networks:
  internal:
    driver: bridge

volumes:
  grafana-storage:

